# Dockerfile MLRules
# Usando a imagem base do Python 3.12.8
FROM python:3.12.8-slim

# Definindo o diretório de trabalho
WORKDIR /app

# Copiando o arquivo de requisitos específico e MLRules.py para o contêiner
COPY requirements.MLRules.txt .
COPY MLRules.py .

# Instalando as dependências
RUN pip install --no-cache-dir -r requirements.MLRules.txt

# Comando para executar MLRules.py
CMD ["python", "MLRules.py"]
