apiVersion: v1
kind: Service
metadata:
  name: mlserver-service
spec:
  type: LoadBalancer  # Change to NodePort if you prefer
  selector:
    app: mlserver
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 5000  # Port your container listens on
