apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlserver
  template:
    metadata:
      labels:
        app: mlserver
    spec:
      containers:
      - name: mlserver-container
        image: carloslage67/cloud_computing_tp2:mlserver
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data-volume
          mountPath: /app/data  # Mount the PVC here
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: my-volume-claim  # Reference the name of your PVC