apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlserver
  template:
    metadata:
      labels:
        app: mlserver
    spec:
      containers:
      - name: mlserver-container
        image: carloslage67/cloud_computing_tp2:mlserver
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"  # Adjust this based on your cluster's available resources
          limits:
            memory: "256Mi"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: project2-pv-carloslage-claim