apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-persistent-volume  # Name for your PV
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/docker/volumes/my_volume/_data  # Path from the volume inspect command