apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume-claim
  namespace: carloslage  # Your Kubernetes namespace
spec:
  accessModes:
    - ReadWriteMany  # This should match the PV's access mode
  resources:
    requests:
      storage: 500Mi  # This should match or be less than the PV capacity
  storageClassName: default-storage-class-carloslage  # Change this to your required format
  selector:
    matchLabels:
      type: local  # Ensure this matches the label on the PV