apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume-claim
  namespace: carloslage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi  # Adjust storage size as needed
  selector:
    matchLabels:
      type: local