apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume-claim
  namespace: carloslage
spec:
  accessModes:
    - ReadWriteMany  # Ensure it matches the PV access mode
  resources:
    requests:
      storage: 1Gi  # Specify the storage size
  selector:
    matchLabels:
      type: local  # Adjust this if needed based on your PV's labels