apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume-claim  # Name for your PVC
  namespace: carloslage   # Use your namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Must match the PV capacity